version: '3.4'

services:
  backend:
    image: ${DOCKER_REGISTRY-}backend
    container_name: backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      #- ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=5803
      - ASPNETCORE_Kestrel__Certificates__Default__Password=pa55w0rd!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/backend.pfx
    ports: 
      - "0.0.0.0:5800:80"
      - "0.0.0.0:5803:443"
    volumes:
      #- ${APPDATA}\Microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https\:/root/.aspnet/https/ 
    networks:
      - my-network
 
networks:
  my-network:
    external: true